In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn import datasets
from sklearn.model_selection import KFold

In [25]:
iris= datasets.load_iris()
X= iris.data
y=iris.target

In [26]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [27]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3]:
#splitting of dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [4]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [5]:
def relu(x):
    return np.maximum(0,x)

def sigmoid(x):
    return 1/(1+ np.exp(-x))

In [6]:
class ELMClassifier:
    def __init__(self, input_size, hidden_size, output_size):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        self.weights_input_hidden = np.random.rand(hidden_size, input_size)
        self.bias_hidden = np.random.rand(hidden_size, 1)
        self.activation_function = relu
        self.output_activation = sigmoid
        
    def train(self, X, y):
        H = self.activation_function(np.dot(self.weights_input_hidden, X.T) + self.bias_hidden)

        # Handle different encodings for y_train
        if len(np.unique(y)) == 2:  # Binary classification
            H_pseudo_inverse = np.linalg.pinv(H.T)
            self.output_weights = np.dot(H_pseudo_inverse, y.reshape(-1, 1))
        else:  # Multi-class classification
            # Convert integer labels to one-hot encoding
            y_one_hot = np.eye(self.output_size)[y]
            H_pseudo_inverse = np.linalg.pinv(H.T)
            self.output_weights = np.dot(H_pseudo_inverse, y_one_hot)

    def predict(self, X):
        H = self.activation_function(np.dot(self.weights_input_hidden, X.T) + self.bias_hidden)
        raw_output = np.dot(H.T, self.output_weights)
        predictions = self.output_activation(raw_output)
        
        # For binary classification, return 0 or 1
        if self.output_size == 1:
            return np.round(predictions).astype(int).flatten()
        else:
            return np.argmax(predictions, axis=1)
        
        

In [7]:
y_train

array([0, 2, 1, 2, 0, 2, 1, 1, 0, 1, 2, 0, 0, 2, 1, 0, 1, 2, 2, 1, 2, 0,
       0, 0, 0, 0, 2, 0, 1, 2, 2, 0, 2, 1, 2, 1, 0, 1, 1, 2, 2, 1, 2, 1,
       2, 2, 0, 2, 2, 0, 2, 0, 1, 2, 1, 1, 1, 0, 2, 0, 1, 1, 1, 1, 1, 1,
       2, 0, 0, 0, 1, 1, 2, 1, 2, 2, 2, 1, 0, 0, 0, 1, 0, 1, 1, 1, 2, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 2, 1, 2, 0, 1, 1, 0, 0, 1, 2, 2, 2, 1,
       2, 1, 0, 0, 0, 2, 1, 2, 2, 1])

In [8]:
kfold = KFold(n_splits=10, shuffle=True, random_state=42)

In [9]:
accuracies = []

In [14]:
hidden_nodes_ranges=[10,20,30,40,50,60,70,80,90,100,200,300]

best_hidden_nodes=None
best_accuracy=0.0

for hidden_nodes in hidden_nodes_ranges:
    print(f"Training model with {hidden_nodes} hidden nodes...")
    
    accuracies=[]
    kfold = KFold(n_splits=5, shuffle=True)
    
    
    for train_index, test_index in kfold.split(X, y):
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]

        # Create and initialize the ELM classifier
        elm_classifier = ELMClassifier(input_size=X_train.shape[1], hidden_size=hidden_nodes, output_size=len(np.unique(y)))

        # Train the ELM classifier
        elm_classifier.train(X_train, y_train)

        # Make predictions
        predictions = elm_classifier.predict(X_test)

        # Evaluate accuracy and store it
        accuracy = accuracy_score(y_test, predictions)
        accuracies.append(accuracy)
        
    avg_accuracy = np.mean(accuracies)
    print(f"Average Accuracy: {avg_accuracy}")
    
    if avg_accuracy > best_accuracy:
            best_accuracy = avg_accuracy
            best_hidden_nodes = hidden_nodes


print(f"Best model has {best_hidden_nodes} hidden nodes with an accuracy of {best_accuracy}")


Training model with 10 hidden nodes...
Average Accuracy: 0.8533333333333333
Training model with 20 hidden nodes...
Average Accuracy: 0.82
Training model with 30 hidden nodes...
Average Accuracy: 0.8400000000000001
Training model with 40 hidden nodes...
Average Accuracy: 0.82
Training model with 50 hidden nodes...
Average Accuracy: 0.8333333333333334
Training model with 60 hidden nodes...
Average Accuracy: 0.8400000000000001
Training model with 70 hidden nodes...
Average Accuracy: 0.8466666666666667
Training model with 80 hidden nodes...
Average Accuracy: 0.8466666666666665
Training model with 90 hidden nodes...
Average Accuracy: 0.82
Training model with 100 hidden nodes...
Average Accuracy: 0.8266666666666665
Training model with 200 hidden nodes...
Average Accuracy: 0.8333333333333334
Training model with 300 hidden nodes...
Average Accuracy: 0.8400000000000001
Best model has 10 hidden nodes with an accuracy of 0.8533333333333333


In [15]:
average_accuracy = np.mean(accuracies)
print(f'Average Accuracy (k-fold cross-validation): {average_accuracy * 100:.2f}%')

Average Accuracy (k-fold cross-validation): 84.00%


In [18]:
accuracy= accuracy_score(y_test, predictions)
print(f'Accuracy: {accuracy * 100: .2f}%')

Accuracy:  93.33%


K-fold cross validation

In [19]:
from sklearn.datasets import load_iris

In [23]:
iris_df= load_iris()
y=iris_df.target


In [24]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [28]:
indicies =  list(range(len(y)))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149]